#!/bin/sh
#
# ifup hook script for resolvconf
#
# This file is part of the resolvconf package.
#

case "$METHOD" in
  manual) : ;;
  *) exit 0 ;;
esac

case "$ADDRFAM" in
  inet6) : ;;
  *) exit 0 ;;
esac

if [ "$IF_FQDNDHCP" ] ; then
	#echo up `date` $IFACE/$LOGICAL $ADDRFAM $METHOD $MODE $PHASE $IF_FQDNDHCP >> /tmp/fqdn
	cp /etc/dhcp/dhclient.conf /var/lib/dhcp/dhclient6.$IFACE.conf
	echo send fqdn.fqdn $IF_FQDNDHCP\; >>/var/lib/dhcp/dhclient6.$IFACE.conf
	/lib/ifupdown/wait-for-ll6.sh
	/sbin/dhclient -6 -pf /run/dhclient6.$IFACE.pid -lf /var/lib/dhcp/dhclient6.$IFACE.leases \
		-df /var/lib/dhcp/dhclient.$IFACE.leases \
		-cf /var/lib/dhcp/dhclient6.$IFACE.conf $IFACE
fi

